### ISSUE TITLE
Automattic hosting compatibility

### ISSUE THREAD

**Issue by cmjaimet** [jamesrwilliams/feature-flags#8]
I was just about to write a plugin like this to use on Automattic's VIP hosting service, but yours does most of what I wanted already. I've forked it and I'd like to modify it so it passes VIP coding requirements. Mostly it's escaping, spacing, explicit conditionals, stuff like that. Please let me know if you have any concerns with this.

Thanks,
Charles

**Comment by philipjohn** [comment]
For context, this is related to the [VIP Coding Standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/), most of which are checked by the [VIP Coding Standards PHPCS ruleset](https://github.com/Automattic/VIP-Coding-Standards).

**Comment by philipjohn** [comment]
There are actually very few issues:

```
PHP CODE SNIFFER REPORT SUMMARY
--------------------------------------------------------------------------------------------------
FILE                                                                              ERRORS  WARNINGS
--------------------------------------------------------------------------------------------------
/home/philipjohn/feature-flags/feature-flags/feature-flags.php                    2       3
/home/philipjohn/feature-flags/feature-flags/assets/css/feature-flags.css         0       1
/home/philipjohn/feature-flags/feature-flags/assets/js/feature-flags.js           0       1
/home/philipjohn/feature-flags/feature-flags/includes/admin/settings-page.php     2       0
/home/philipjohn/feature-flags/src/js/feature-flags.js                            2       1
--------------------------------------------------------------------------------------------------
A TOTAL OF 6 ERRORS AND 6 WARNINGS WERE FOUND IN 5 FILES
--------------------------------------------------------------------------------------------------

Time: 192ms; Memory: 8Mb
```

**Comment by jamesrwilliams** [comment]
Hi @cmjaimet & @philipjohn. I'll work to fix the standards issues highlighted ASAP to get this working on WordPress VIP.

**Comment by jamesrwilliams** [comment]
Code should now conform to the VIP standards. Haven't been able to find much useful documentation on the `*_user_attribute()` vs `*_user_meta()` differences between standalone and VIP WordPress so any guidance you have would be appreciated.

I've written a wrapper but I'm not sure if it is suitable. See [class-featureflags.php#L240-L281](https://github.com/jamesrwilliams/feature-flags/blob/develop/feature-flags/includes/class-featureflags.php#L240-L281).

**Comment by cmjaimet** [comment]
Cool, thanks James. I've made a whole lot of changes that may have more to do with my needs than yours but I'll share them with you shortly. One of the main ones is moving from user meta to options. My need is to create a beta flag that affects the experience for regular users, so I can deploy new features but ave them turned off by default.

**Comment by cmjaimet** [comment]
https://github.com/cmjaimet/beta-flags

Still needs unit testing but it's done other than that.
